language: go

go:
  - 1.7
  - tip

os:
  - linux
  - osx

before_install:
  - go get github.com/mitchellh/gox

script:
  - go test -v -race ./...

before_deploy:
  - gox -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" ./cmd/gopkgs/

deploy:
  provider: releases
  api_key:
    secure: Xu5JeWMXv29Bz0VLk8lX1pFphyGLF2RciuG7umnRdNVGOEvz2jhNm+IRjNn8FCm7Y0PKaOOCGHCDH3qti2tcl8tY+MWxD8E1UpoqfvunKsVqhy5gLbJu39jBOmlSKJe/+k1s1YIkRz6Ie0+oEQEM3I/Hlruk51DA91i/2/mdA/Zea1Pp6hhO/BKvp/tQ6YJEsLAt0DLLueGoNl8X/XDPsLA501qiy4AO+CskLanvcegVoh32k9XCRauHmkfvxkHQsEIQnaG5jVuEiFISyVDZv+Oa3uXXLS37J03Gyw1/NcS8gwAtD/YpgrXKaF00NPWyRwPA8opGUeACAeOnNshyM+/9khKmVS7sS4yeNyYF6H+Tf/h6TnIEy3ltqMc6ERdkL0JB6vDU9ReR0tzoh5SjzgPvv2BnxXP+Uwqx0i9kWU2kBiklJ7Kh8KaRt0Hd0fKsLnT+uzdCUFwOHyF56cAfrUJxrS9sZitQoPkB22rhSlbwMRzn1L3WmZh8tUW+Jct1hUDlM1x4yhkgFP4FRaXF3jChiOmEUPZymArBZY2NoPGeGfuCqo05XSwyO3YIbgN63OdzcJMmGS8LTSjoy1b5epRKOosSOHzzUTieu04pxFTyzcitWUqsAKaAZrAsWsThNfnAM9+Dr+u2+xxabLfAoqo8kh6FUEWm6DAD/cGPM90=
  file:
    - dist/gopkgs_darwin_386
    - dist/gopkgs_darwin_amd64
    - dist/gopkgs_freebsd_386
    - dist/gopkgs_freebsd_amd64
    - dist/gopkgs_freebsd_arm
    - dist/gopkgs_linux_386
    - dist/gopkgs_linux_amd64
    - dist/gopkgs_linux_arm
    - dist/gopkgs_netbsd_386
    - dist/gopkgs_netbsd_amd64
    - dist/gopkgs_netbsd_arm
    - dist/gopkgs_openbsd_386
    - dist/gopkgs_openbsd_amd64
    - dist/gopkgs_windows_386.exe
    - dist/gopkgs_windows_amd64.exe
  skip_cleanup: true
  on:
    tags: true
